name: Readable-readme

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Readable Readme
      uses: tianhaoz95/readable-readme@v1.0.4-beta
      with:
        token: a5ca94c555df6dcf80755ef67655408374f14602
