name: Launch tests
on: push

jobs:
  Unit_testing:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Config
        run: brew update && brew install git && curl --show-error --silent https://getcomposer.org/installer | php && php composer.phar install --no-scripts --no-progress

      - name: Unit testing
        run: make unit_test

  Integration_testing:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Congig
        run: brew update && brew install git && curl --show-error --silent https://getcomposer.org/installer | php && php composer.phar install --no-scripts --no-progress

      - name: Integration testing
        run: make integration_test

  testFunctional:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Config
        run: brew update && brew install git && curl --show-error --silent https://getcomposer.org/installer | php && php composer.phar --no-scripts --no-progress

      - name: Functional testing
        run: make functional_test
